# Generated by Django 5.1.1 on 2024-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
