# Generated by Django 5.1.1 on 2024-09-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_college_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'managed': False},
        ),
    ]
